const mockStudents = [
  {
    id: "s1",
    name: "Aisha Patel",
    email: "aisha.patel@usc.edu",
    university: "USC",
    major: "Computer Science",
    minor: "Data Science",
    graduationYear: "2025",
    location: "Los Angeles, CA",
    skills: ["Python", "Machine Learning", "React", "SQL", "TensorFlow"],
    bio: "Passionate about applying AI to real-world problems. Previously interned at a health tech startup.",
    profilePicture: "https://placehold.co/120x120/FF6B00/white?text=AP",
    resume: "Aisha_Patel_Resume.pdf",
    teamId: "t1",
    profileComplete: true
  },
  {
    id: "s2",
    name: "Marcus Chen",
    email: "marcus.chen@usc.edu",
    university: "USC",
    major: "Electrical Engineering",
    minor: "Computer Science",
    graduationYear: "2025",
    location: "Los Angeles, CA",
    skills: ["C++", "Embedded Systems", "CAD", "MATLAB", "Python"],
    bio: "Hardware-software integration enthusiast. Experience with drone systems and robotics.",
    profilePicture: "https://placehold.co/120x120/FF8C42/white?text=MC",
    resume: "Marcus_Chen_Resume.pdf",
    teamId: "t1",
    profileComplete: true
  },
  {
    id: "s3",
    name: "Sofia Ramirez",
    email: "sofia.ramirez@usc.edu",
    university: "USC",
    major: "Business Administration",
    minor: "Environmental Studies",
    graduationYear: "2026",
    location: "San Francisco, CA",
    skills: ["Project Management", "Data Analysis", "Excel", "Sustainability", "Market Research"],
    bio: "Bridging business strategy and sustainability. Looking to create impact through industry partnerships.",
    profilePicture: "https://placehold.co/120x120/FF6B00/white?text=SR",
    resume: "Sofia_Ramirez_Resume.pdf",
    teamId: "t2",
    profileComplete: true
  },
  {
    id: "s4",
    name: "Jordan Kim",
    email: "jordan.kim@usc.edu",
    university: "USC",
    major: "Biomedical Engineering",
    minor: null,
    graduationYear: "2025",
    location: "Los Angeles, CA",
    skills: ["Python", "R", "Clinical Data", "MATLAB", "Biostatistics"],
    bio: "Focused on healthcare innovation. Research background in wearable biosensors.",
    profilePicture: "https://placehold.co/120x120/FF8C42/white?text=JK",
    resume: "Jordan_Kim_Resume.pdf",
    teamId: "t2",
    profileComplete: true
  },
  {
    id: "s5",
    name: "Tyler Brooks",
    email: "tyler.brooks@usc.edu",
    university: "USC",
    major: "Computer Science",
    minor: "Film Production",
    graduationYear: "2026",
    location: "Los Angeles, CA",
    skills: ["JavaScript", "React", "Node.js", "UI/UX", "Figma"],
    bio: "Full-stack developer with a creative edge. Building digital experiences that matter.",
    profilePicture: "https://placehold.co/120x120/FF6B00/white?text=TB",
    resume: "Tyler_Brooks_Resume.pdf",
    teamId: null,
    profileComplete: false
  }
];

// Logged-in student mock (current user)
const currentStudent = {
  id: "s_me",
  name: "Alex Johnson",
  email: "alex.johnson@usc.edu",
  university: "USC",
  major: "Computer Science",
  minor: "Mathematics",
  graduationYear: "2025",
  location: "Los Angeles, CA",
  skills: ["Python", "React", "Machine Learning", "SQL", "Node.js"],
  bio: "Aspiring software engineer passionate about building products that scale. Looking for capstone projects in AI/ML or fintech.",
  profilePicture: "https://placehold.co/120x120/FF6B00/white?text=AJ",
  resume: null,
  teamId: "t1",
  profileComplete: true
};
