const mockProjects = [
  {
    id: "p1",
    companyId: "c1",
    companyName: "AeroVance Systems",
    companyLogo: "https://placehold.co/40x40/1a1a2e/white?text=AV",
    title: "Autonomous Drone Collision Avoidance via Computer Vision",
    topic: "Artificial Intelligence",
    scope: "Develop a real-time object detection and avoidance module for autonomous UAVs operating in urban airspace using computer vision and sensor fusion.",
    timeline: "Jan 2025 – May 2025",
    location: "El Segundo, CA (Hybrid)",
    problemStatement: "Urban drone delivery faces critical safety challenges. We need a lightweight CV model that can run on embedded hardware with <50ms latency while maintaining >95% obstacle detection accuracy.",
    requiredSkills: ["Python", "Computer Vision", "TensorFlow", "Embedded Systems", "MATLAB"],
    status: "open",
    applicantCount: 4,
    acceptedTeams: [],
    isDraft: false,
    createdAt: "2024-11-01"
  },
  {
    id: "p2",
    companyId: "c1",
    companyName: "AeroVance Systems",
    companyLogo: "https://placehold.co/40x40/1a1a2e/white?text=AV",
    title: "Predictive Maintenance ML Pipeline for Jet Engine Components",
    topic: "Machine Learning",
    scope: "Build an end-to-end ML pipeline that predicts component failure using sensor telemetry from turbofan engines. Integrate with existing MRO workflow.",
    timeline: "Feb 2025 – Jun 2025",
    location: "Remote",
    problemStatement: "Unplanned maintenance events cost the aerospace industry billions annually. We need a model that can identify failure signatures 200+ flight hours in advance.",
    requiredSkills: ["Python", "Machine Learning", "SQL", "Data Engineering", "Time Series Analysis"],
    status: "in-progress",
    applicantCount: 6,
    acceptedTeams: ["t1"],
    isDraft: false,
    createdAt: "2024-10-15"
  },
  {
    id: "p3",
    companyId: "c2",
    companyName: "Lumina Health",
    companyLogo: "https://placehold.co/40x40/0d7377/white?text=LH",
    title: "AI-Powered Anomaly Detection for Wearable Patient Vitals",
    topic: "Healthcare AI",
    scope: "Design a clinical-grade anomaly detection system that flags irregular heart rate, SpO2, and respiration patterns from continuous wearable data streams.",
    timeline: "Jan 2025 – May 2025",
    location: "San Diego, CA (On-site)",
    problemStatement: "Remote patients experience deterioration events that go undetected for hours. We need real-time alerting that minimizes false positives while catching true clinical deterioration.",
    requiredSkills: ["Python", "R", "Biostatistics", "Machine Learning", "Clinical Data"],
    status: "open",
    applicantCount: 3,
    acceptedTeams: [],
    isDraft: false,
    createdAt: "2024-11-10"
  },
  {
    id: "p4",
    companyId: "c2",
    companyName: "Lumina Health",
    companyLogo: "https://placehold.co/40x40/0d7377/white?text=LH",
    title: "Patient Engagement Dashboard Redesign",
    topic: "UX/Product",
    scope: "Redesign the patient-facing mobile dashboard to improve engagement, medication adherence tracking, and care plan visibility.",
    timeline: "Mar 2025 – Jun 2025",
    location: "Remote",
    problemStatement: "Our current patient app has 34% DAU/MAU ratio. We need a redesign grounded in health behavior research that drives daily active usage and reduces care gaps.",
    requiredSkills: ["UI/UX", "Figma", "React", "User Research", "JavaScript"],
    status: "open",
    applicantCount: 5,
    acceptedTeams: [],
    isDraft: false,
    createdAt: "2024-11-20"
  },
  {
    id: "p5",
    companyId: "c3",
    companyName: "Verdant Advisory",
    companyLogo: "https://placehold.co/40x40/2d6a4f/white?text=VA",
    title: "Carbon Accounting Automation Tool for Scope 3 Emissions",
    topic: "Sustainability",
    scope: "Build a data pipeline and reporting tool that automates Scope 3 GHG inventory collection across supplier tiers using EPA and GHG Protocol standards.",
    timeline: "Jan 2025 – May 2025",
    location: "San Francisco, CA (Hybrid)",
    problemStatement: "Clients spend 3–6 months manually collecting supplier emissions data. We need an automated ingestion, normalization, and reporting solution to reduce this to 2 weeks.",
    requiredSkills: ["Python", "SQL", "Data Engineering", "Sustainability", "Excel"],
    status: "open",
    applicantCount: 2,
    acceptedTeams: [],
    isDraft: false,
    createdAt: "2024-12-01"
  },
  {
    id: "p6",
    companyId: "c3",
    companyName: "Verdant Advisory",
    companyLogo: "https://placehold.co/40x40/2d6a4f/white?text=VA",
    title: "Net-Zero Transition Scenario Modeling Platform",
    topic: "Sustainability",
    scope: "Develop an interactive scenario modeling tool that lets clients visualize different decarbonization pathways and their financial trade-offs through 2050.",
    timeline: "Completed Spring 2024",
    location: "Remote",
    problemStatement: "Executives lack intuitive tools to understand the cost and timeline trade-offs of different net-zero pathways. Static slide decks don't communicate complexity.",
    requiredSkills: ["JavaScript", "Data Visualization", "React", "Sustainability", "Market Research"],
    status: "completed",
    applicantCount: 4,
    acceptedTeams: ["t2"],
    isDraft: false,
    createdAt: "2024-01-15"
  }
];